export const BALL8_RESPONSES: { text: string; type: 'positive' | 'neutral' | 'negative' }[] = [
  { text: 'Los astros dicen que la Fortaleza aprueba 🔮', type: 'positive' },
  { text: 'Sin duda, el camino está despejado ⚔️', type: 'positive' },
  { text: 'Es seguro, como los muros de la Fortaleza 🏰', type: 'positive' },
  { text: 'Los vientos del norte soplan a tu favor 🌬️', type: 'positive' },
  { text: 'El Señor de la Fortaleza dice que sí 👑', type: 'positive' },
  { text: 'Las estrellas lo confirman ✨', type: 'positive' },
  { text: 'Buena fortuna te espera en el horizonte 🗡️', type: 'positive' },
  { text: 'El oráculo habla con voz clara: sí 🔮', type: 'positive' },
  { text: 'Los dioses protegen tu camino 🙏', type: 'positive' },
  { text: 'Tu destino es favorable, valiente caballero ⚔️', type: 'positive' },
  { text: 'La Fortaleza aprueba tu pregunta sin dudarlo 🏰', type: 'positive' },
  { text: 'El escudo brillante indica buena suerte 🛡️', type: 'positive' },
  { text: 'Consulta al Señor de la Fortaleza más tarde 🕐', type: 'neutral' },
  { text: 'La niebla oculta la respuesta... pregunta de nuevo 🌫️', type: 'neutral' },
  { text: 'El viento no se decide, ni yo tampoco 🌬️', type: 'neutral' },
  { text: 'Los pergaminos antiguos permanecen en silencio 📜', type: 'neutral' },
  { text: 'La respuesta se perdió en el laberinto del castillo 🏰', type: 'neutral' },
  { text: 'Ni los Guardianes tienen la respuesta ahora 🛡️', type: 'neutral' },
  { text: 'La Fortaleza no comparte sus secretos hoy 🏰', type: 'neutral' },
  { text: 'Los caminos se cruzan, la respuesta no está clara 🗺️', type: 'neutral' },
  { text: 'No cuentes con ello, viajero 🚫', type: 'negative' },
  { text: 'Los muros de la Fortaleza se cierran ante tu pregunta 🏰', type: 'negative' },
  { text: 'La suerte no está de tu lado hoy 🎲', type: 'negative' },
  { text: 'El oráculo niega tu petición 🔮', type: 'negative' },
  { text: 'Los vientos del sur traen mal presagio 🌫️', type: 'negative' },
  { text: 'Tu pregunta ha sido rechazada por el concilio 🛡️', type: 'negative' },
  { text: 'Ni el Forjador de Leyendas podría arreglar esto 🔨', type: 'negative' },
  { text: 'Mejor busca otro camino, este está bloqueado 🚧', type: 'negative' },
];

export const BALL8_COLORS: Record<string, number> = {
  positive: 0x27ae60,
  neutral: 0xf39c12,
  negative: 0xe74c3c,
};