export const TRUTHS: string[] = [
  '¿Cuál es tu juego favorito de todos los tiempos?',
  '¿Qué canción escuchas en secreto pero no admitirías jamás?',
  '¿Cuál es la película que más te ha hecho llorar?',
  '¿Qué talento oculto tienes que nadie en el servidor conoce?',
  '¿Cuál es tu mayor arrepentimiento gaming?',
  '¿Qué personaje de ficción te gustaría ser y por qué?',
  '¿Cuál es la cosa más geek que has hecho?',
  '¿Qué libro o historia te cambió la vida?',
  '¿Cuál es tu mayor miedo?',
  '¿Qué superpoder elegirías si pudieras tener uno?',
  '¿Qué persona del servidor crees que sería un buen líder de una misión?',
  '¿Cuál es tu comida favorita de la medieval?',
  '¿Qué habilidad te gustaría aprender pero nunca has intentado?',
  '¿Cuál es tu mayor phielper en videojuegos?',
  '¿Si pudieras viajar en el tiempo, a qué época irías?',
  '¿Qué es lo primero que harías si despertaras en una fortaleza medieval?',
  '¿Cuál es tu memoria más divertida en un juego online?',
  '¿Qué cosa te da vergüenza admitir que te gusta?',
  '¿Cuál es tu personaje de RPG favorito (clase/tipo)?',
  '¿Qué hobby tendrías en una vida medieval?',
  '¿Qué es lo más valiente que has hecho?',
  '¿Qué secreto tienes que solo tú conoces?',
  '¿Si pudieras cambiar una cosa del servidor, qué sería?',
  '¿Qué miembro del servidor te gustaría conocer en persona?',
  '¿Cuál es tu mayor meta en la vida?',
  '¿Qué cosa simple te hace más feliz?',
  '¿Qué es lo más raro que has comido?',
  '¿Cuál es tu serie o anime favorito que recomiendas a todos?',
  '¿Qué le dirías a tu yo del passado?',
  '¿Qué es lo que más valoras en una amistad?',
];

export const DARES: string[] = [
  'Envía un mensaje con un emoji aleatorio al canal general',
  'Cambia tu apodo a "Caballero de la Fortaleza" por 10 minutos',
  'Escribe un poema de 2 líneas sobre la Fortaleza y envíalo al chat',
  'Menciona a la última persona que te habló y dile algo amable',
  'Comparte tu canción favorita en el chat de música',
  'Escribe "¡Los muros de la Fortaleza son increíbles!" en mayúsculas',
  'Describe tu día usando solo emojis',
  'Escribe un cumplido para el primer miembro que aparezca en la lista',
  'Manda un meme en el chat (apropiado para todo público)',
  'Imagina que eres un NPC de la Fortaleza y habla como él por 5 minutos',
  'Escribe qué clase de RPG serías y por qué',
  'Dile a alguien del servidor cuál es su mejor cualidad',
  'Canta (escribe la letra de) tu canción favorita en el chat',
  'Escribe una historia de 3 líneas que empiece con "Érase una vez en la Fortaleza..."',
  'Haz una predicción sobre el próximo mensaje que alguien envíe',
  'Comparte un dato curioso que sepas sobre la Edad Media',
  'Escribe un insulto creativo estilo medieval (sin ofender realmente)',
  'Dibuja (describe con palabras) tu escudo de armas familiar',
  'Escribe qué 3 cosas llevarías a una isla desierta',
  'Nombra 3 cosas que te gusten del servidor',
  'Escribe tu nombre al revés y úsalo como apodo por 5 minutos',
  'Describe tu comida ideal sin usar nombres de comida',
  'Escribe qué hechizo mágico te gustaría tener en la vida real',
  'Inventa una pocion mágica y describe sus ingredientes',
  'Escribe qué tipo de criatura mítica serías y por qué',
  'Comparte una frase motivadora en el chat',
  'Haz una recomendación de juego al chat',
  'Escribe un cumplido para ti mismo (¡mereces reconocimiento!)',
  'Describe la Fortaleza perfecta en 3 palabras',
  'Di "gracias" a alguien del servidor por algo específico',
];